# Generated by Django 4.1.3 on 2022-12-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_alter_authordetail_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authordetail',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
