# Generated by Django 4.1.3 on 2022-12-17 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_alter_authordetail_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name_plural': '作者'},
        ),
        migrations.AlterModelOptions(
            name='authordetail',
            options={'verbose_name_plural': '作者详情'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name_plural': '书'},
        ),
        migrations.AlterModelOptions(
            name='publish',
            options={'verbose_name_plural': '出版社'},
        ),
        migrations.AlterField(
            model_name='author',
            name='authordetail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app01.authordetail', verbose_name='作者详情'),
        ),
        migrations.AlterField(
            model_name='author',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='author',
            name='gender',
            field=models.IntegerField(choices=[(1, '男'), (2, '女'), (3, '保密')], verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='author',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='最近一次修改时间'),
        ),
        migrations.AlterField(
            model_name='authordetail',
            name='add',
            field=models.CharField(max_length=128, verbose_name='作者地址'),
        ),
        migrations.AlterField(
            model_name='authordetail',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='authordetail',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='authordetail',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='最近一次修改时间'),
        ),
        migrations.AlterField(
            model_name='authordetail',
            name='phone',
            field=models.BigIntegerField(verbose_name='电话号码'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(db_constraint=False, to='app01.author', verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='book',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='book',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='最近一次修改时间'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publish',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='app01.publish', verbose_name='出版社'),
        ),
        migrations.AlterField(
            model_name='publish',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='publish',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='publish',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='最近一次修改时间'),
        ),
    ]
