# Generated by Django 4.1 on 2022-08-13 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='hobby',
            field=models.CharField(default='games', max_length=32, verbose_name='兴趣'),
        ),
        migrations.AddField(
            model_name='author',
            name='info',
            field=models.CharField(max_length=32, null=True, verbose_name='备注'),
        ),
    ]
