# Generated by Django 4.1.3 on 2022-11-18 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='BookName')),
                ('publishing', models.CharField(max_length=64, verbose_name='Publishing Company')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('author', models.CharField(max_length=32)),
            ],
        ),
    ]
