# Generated by Django 4.1.3 on 2022-11-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('age', models.IntegerField(max_length=3, verbose_name='年龄')),
                ('score', models.IntegerField(choices=[(5, 'E'), (1, 'A'), (4, 'D'), (2, 'B'), (3, 'C')])),
            ],
        ),
    ]
