# Generated by Django 4.1.3 on 2022-12-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_loginuser_usertoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginuser',
            name='usertype',
            field=models.IntegerField(choices=[(1, '超级管理员'), (2, '管理员'), (3, '普通用户'), (4, '受限用户')], default=2),
            preserve_default=False,
        ),
    ]
