# Generated by Django 4.1 on 2022-09-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('age', models.IntegerField()),
                ('gender', models.IntegerField(choices=[(1, '男'), (2, '女'), (3, '其他')])),
                ('score', models.CharField(choices=[('A', '优秀'), ('B', '良好'), ('C', '及格'), ('D', '不合格')], max_length=32, null=True)),
            ],
        ),
    ]
