# Generated by Django 4.1 on 2022-09-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_te'),
    ]

    operations = [
        migrations.AlterField(
            model_name='te',
            name='job',
            field=models.CharField(blank=True, default='IT', max_length=32, null=True, verbose_name='职业'),
        ),
    ]
