# Generated by Django 4.1 on 2022-09-18 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_alter_te_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='te',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.te'),
            preserve_default=False,
        ),
    ]
